#!/usr/bin/env bash

# define a function to get DNS configuration
get_dns_config () {
    domain=$1
    subdomain=$2
    response=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$subdomain $response" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# check the number of arguments passed to the script
if [ "$#" == 1 ]
then
  # if only one argument is passed, check the DNS configuration for the standard subdomains
  get_dns_config "$1" "www"
  get_dns_config "$1" "lb-01"
  get_dns_config "$1" "web-01"
  get_dns_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  # if two arguments are passed, check the DNS configuration for the specified domain and subdomain
  get_dns_config "$1" "$2"
fi
