#!/usr/bin/env bash
# Debugging code to check if Nginx is not running
# Replace the port number 8080 with 80 in the Nginx configuration file
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
# Restart the Nginx service
service nginx restart
# Kill any other running Nginx processes
pkill -o nginx
